services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      TZ: 'America/Campo_Grande'
    ports:
      - "${DB_PORT}:5432"
    networks:
      - my_network
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

networks:
  my_network:
    driver: bridge

volumes:
  dbdata: {}
  redis_data: {}

