services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      TZ: 'America/Campo_Grande'
    ports:
      - "${DB_PORT}:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  dbdata: {}
